services:
  - type: web
    name: sentiment-api
    runtime: python
    buildCommand: >
      pip install --upgrade pip &&
      pip install -r requirements.txt
      # If torch fails on your instance, use this instead:
      # && pip install torch --index-url https://download.pytorch.org/whl/cpu
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 2
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: MODEL_NAME
        value: distilbert-base-uncased-finetuned-sst-2-english
      - key: NEUTRAL_THRESHOLD
        value: "0.6"
      - key: MAX_BATCH
        value: "64"
      - key: HF_HOME
        value: /var/cache/huggingface
    disk:
      name: hf-cache
      mountPath: /var/cache/huggingface
      sizeGB: 4
